'use strict';

const languages = {
    'zb': {
        'en': {
            'Time Interval': 'Time Interval',
            'Price Change': 'Price Change',
            'Min': 'Min',
            'Max': 'Max',
            'Refresh': 'Refresh',
            'Currency': 'Currency',
            'Last Price': 'Last Price',
            'Volume': 'Volume',
            'Volume Change': 'Volume Change',
            'Since Opened': 'Since Opened',
            'Acum': 'Accum',
            'AVG': 'AVG',
            'Hide': 'Hide',
            'Show': 'Show',
            'Calculator': 'Calculator',
            'Price': 'Price',
            'Buy': 'Buy',
            'Sell': 'Sell',
            'High': 'High',
            'Low': 'Low',
            'Last': 'Last',
            'Change': 'Change',
            'Improve': 'Improve',
            'Selling': 'Selling',
            'Buying': 'Buying',
            'Depth': 'Depth',
            'Trades': 'Trades',
            'Help Us to Improve': 'Help Us to Improve',
            'WorkingOn': 'We are working fast to give you the best trading tool ever made for huobi global. Our goal is to bring you a unified tool through web and mobile apps that detect early the pump and dump\'s cryptos',
            'Make a donation': 'Please give us your suggestions on how can we improve the browser extension and the mobile app in our <a href="https://github.com/yosietserga" target="_blank">Github Repos</a>. You can make a donation, too.'
        },
        'cn': {
            'Time Interval': '時間間隔',
            'Price Change': '價格變動',
            'Min': '最低限度',
            'Max': '最大值',
            'Refresh': 'Refresh',
            'Currency': '貨幣',
            'Last Price': '最後價格',
            'Volume': '量',
            'Volume Change': '成交量變化',
            'Since Opened': '自開業以來',
            'Acum': '積累',
            'AVG': '平均',
            'Hide': '隱藏',
            'Show': '節目',
            'Calculator': '計算器',
            'Price': '價錢',
            'Buy': '購買',
            'Sell': '賣',
            'High': '最高价',
            'Low': '最低价',
            'Last': '持續',
            'Change': '涨幅',
            'Improve': '提高',
            'Trades': '交易',
            'Help Us to Improve': '帮助我们改进',
            'WorkingOn': '我们正在努力为您提供有史以来为huobi global制作的最佳交易工具. 我们的目标是通过早期检测到的网络和移动应用为您提供统一的工具 the pump and dump\'s cryptos',
            'Make a donation': '请告诉我们您如何在我们的 <a href="https://github.com/yosietserga" target="_blank">Github Repos</a>. 中改进浏览器扩展和移动应用程序的建议. 你也可以捐款'
        }
    },
    'huobi': {
        'en-us': {
            'Time Interval': 'Time Interval',
            'Price Change': 'Price Change',
            'Min': 'Min',
            'Max': 'Max',
            'Refresh': 'Refresh',
            'Currency': 'Currency',
            'Last Price': 'Last Price',
            'Volume': 'Volume',
            'Volume Change': 'Volume Change',
            'Since Opened': 'Since Opened',
            'Acum': 'Accum',
            'AVG': 'AVG',
            'Hide': 'Hide',
            'Show': 'Show',
            'Calculator': 'Calculator',
            'Price': 'Price',
            'Buy': 'Buy',
            'Sell': 'Sell',
            'High': 'High',
            'Low': 'Low',
            'Last': 'Last',
            'Change': 'Change',
            'Improve': 'Improve',
            'Selling': 'Selling',
            'Buying': 'Buying',
            'Depth': 'Depth',
            'Trades': 'Trades',
            'Help Us to Improve': 'Help Us to Improve',
            'WorkingOn': 'We are working fast to give you the best trading tool ever made for huobi global. Our goal is to bring you a unified tool through web and mobile apps that detect early the pump and dump\'s cryptos',
            'Make a donation': 'Please give us your suggestions on how can we improve the browser extension and the mobile app in our <a href="https://github.com/yosietserga" target="_blank">Github Repos</a>. You can make a donation, too.'
        },
        'th-th': {
            'Time Interval': 'ช่วงเวลา',
            'Price Change': 'การเปลี่ยนแปลงราคา',
            'Min': 'ขั้นต่ำ',
            'Max': 'สูงสุด',
            'Refresh': 'รีเฟรช',
            'Currency': 'เงินตรา',
            'Last Price': 'ราคาล่าสุด',
            'Volume': 'ปริมาณ',
            'Volume Change': 'เปลี่ยนระดับเสียง',
            'Since Opened': 'ตั้งแต่เปิด',
            'Acum': 'สะสม',
            'AVG': 'AVG',
            'Hide': 'ปิดบัง',
            'Show': 'แสดง',
            'Calculator': 'เครื่องคิดเลข',
            'Price': 'ราคา',
            'Buy': 'ซื้อ',
            'Sell': 'ขาย',
            'High': 'สูง',
            'Low': 'ต่ำ',
            'Last': 'สุดท้าย',
            'Change': 'เปลี่ยนแปลง',
            'Improve': 'ปรับปรุง',
            'Trades': 'การซื้อขาย',
            'Help Us to Improve': 'ช่วยเราปรับปรุง',
            'WorkingOn': 'เรากำลังทำงานอย่างรวดเร็วเพื่อมอบเครื่องมือการซื้อขายที่ดีที่สุดสำหรับ huobi ทั่วโลก เป้าหมายของเราคือการนำเครื่องมือแบบครบวงจรมาให้คุณผ่านเว็บและแอพมือถือที่ตรวจจับการเข้ารหัสลับของปั๊มและการถ่ายโอนข้อมูลในช่วงต้น',
            'Make a donation': 'โปรดให้คำแนะนำกับเราเกี่ยวกับวิธีที่เราสามารถปรับปรุงส่วนขยายเบราว์เซอร์และแอพมือถือในของเรา <a href="https://github.com/yosietserga" target="_blank">Github Repos</a>. คุณสามารถบริจาคได้เช่นกัน.'
        },
        'tr-tr': {
            'Time Interval': 'Zaman aralığı',
            'Price Change': 'fiyat değişiklikleri',
            'Min': 'Asgari',
            'Max': 'Maksimum',
            'Refresh': 'Yenile',
            'Currency': 'Para birimi',
            'Last Price': 'Son fiyat',
            'Volume': 'Hacim',
            'Volume Change': 'Hacim Değişimi',
            'Since Opened': 'Açıldığından beri',
            'Acum': 'Birikmiş',
            'AVG': 'AVG',
            'Hide': 'Saklamak',
            'Show': 'Göstermek',
            'Calculator': 'Hesap makinesi',
            'Price': 'Fiyat',
            'Buy': 'Satın almak',
            'Sell': 'Satmak',
            'High': 'Yüksek',
            'Low': 'Düşük',
            'Last': 'Son',
            'Change': 'Değişiklik',
            'Improve': 'Iyileştirmek',
            'Trades': 'İşlemler',
            'Help Us to Improve': 'Geliştirmemize Yardım Edin',
            'WorkingOn': 'Size şimdiye kadar huobi global için üretilmiş en iyi yatırım aracını sunmak için hızlı çalışıyoruz. Amacımız, pompanın ve boşaltma kriptolarının erken dönemlerini tespit eden web ve mobil uygulamalar aracılığıyla size birleşik bir araç sunmaktır.',
            'Make a donation': 'Lütfen bize tarayıcı uzantısını ve mobil uygulamamızı <a href="https://github.com/yosietserga" target="_blank">Github Repos</a>. Siz de bağış yapabilirsiniz.'
        },
        'vi-vi': {
            'Time Interval': 'Khoảng thời gian',
            'Price Change': 'Thay đổi giá',
            'Min': 'Tối thiểu',
            'Max': 'Tối đa',
            'Refresh': 'Làm tươi',
            'Currency': 'Tiền tệ',
            'Last Price': 'Giá cuối cùng',
            'Volume': 'Âm lượng',
            'Volume Change': 'Thay đổi âm lượng',
            'Since Opened': 'Kể từ khi mở',
            'Acum': 'Tích lũy',
            'AVG': 'AVG',
            'Hide': 'Ẩn giấu',
            'Show': 'Chỉ',
            'Calculator': 'Máy tính',
            'Price': 'Giá bán',
            'Buy': 'Mua',
            'Sell': 'Bán',
            'High': 'Cao',
            'Low': 'Thấp',
            'Last': 'Cuối cùng',
            'Change': 'Thay đổi',
            'Improve': 'Cải tiến',
            'Trades': 'Giao dịch',
            'Help Us to Improve': 'Giúp chúng tôi cải thiện',
            'WorkingOn': 'Chúng tôi đang làm việc nhanh chóng để cung cấp cho bạn công cụ giao dịch tốt nhất từng được tạo ra cho huobi toàn cầu. Mục tiêu của chúng tôi là mang đến cho bạn một công cụ hợp nhất thông qua các ứng dụng web và di động phát hiện sớm tiền điện tử của máy bơm',
            'Make a donation': 'Vui lòng cho chúng tôi đề xuất của bạn về cách chúng tôi có thể cải thiện tiện ích mở rộng trình duyệt và ứng dụng di động trong <a href="https://github.com/yosietserga" target="_blank">Github Repos</a>. Bạn cũng có thể đóng góp.'
        },
        'pt-br': {
            'Time Interval': 'Intervalo de tempo',
            'Price Change': 'Mudança de preço',
            'Min': 'Min',
            'Max': 'Max',
            'Refresh': 'Atualizar',
            'Currency': 'Moeda',
            'Last Price': 'Último preço',
            'Volume': 'Volume',
            'Volume Change': 'Mudança de volume',
            'Since Opened': 'Desde que abriu',
            'Acum': 'Acumulado',
            'AVG': 'AVG',
            'Hide': 'Ocultar',
            'Show': 'Exposição',
            'Calculator': 'Calculadora',
            'Price': 'Preço',
            'Buy': 'Comprar',
            'Sell': 'Vender',
            'High': 'Alto',
            'Low': 'Baixo',
            'Last': 'Último',
            'Change': 'Mudança',
            'Improve': 'Melhorar',
            'Trades': 'Comércios',
            'Help Us to Improve': 'Ajude-nos a melhorar',
            'WorkingOn': 'Estamos trabalhando rapidamente para oferecer a melhor ferramenta de negociação já feita para o mundo huobi. Nosso objetivo é trazer a você uma ferramenta unificada através de aplicativos web e móveis que detectam precocemente os criptos de bombas e lixões',
            'Make a donation': 'Por favor, dê-nos as suas sugestões sobre como podemos melhorar a extensão do navegador e o aplicativo móvel em nosso <a href="https://github.com/yosietserga" target="_blank">Github Repos</a>. Você pode fazer uma doação também.'
        },
        'pt-pt': {
            'Time Interval': 'Time Interval',
            'Price Change': 'Mudança de preço',
            'Min': 'Min',
            'Max': 'Max',
            'Refresh': 'Atualizar',
            'Currency': 'Moeda',
            'Last Price': 'Último preço',
            'Volume': 'Volume',
            'Volume Change': 'Mudança de volume',
            'Since Opened': 'Desde que abriu',
            'Acum': 'Acumulado',
            'AVG': 'AVG',
            'Hide': 'Ocultar',
            'Show': 'Exposição',
            'Calculator': 'Calculadora',
            'Price': 'Preço',
            'Buy': 'Comprar',
            'Sell': 'Vender',
            'High': 'Alto',
            'Low': 'Baixo',
            'Last': 'Último',
            'Change': 'Mudança',
            'Improve': 'Melhorar',
            'Trades': 'Comércios',
            'Help Us to Improve': 'Ajude-nos a melhorar',
            'WorkingOn': 'Estamos trabalhando rapidamente para oferecer a melhor ferramenta de negociação já feita para o mundo huobi. Nosso objetivo é trazer a você uma ferramenta unificada através de aplicativos web e móveis que detectam precocemente os criptos de bombas e lixões',
            'Make a donation': 'Por favor, dê-nos as suas sugestões sobre como podemos melhorar a extensão do navegador e o aplicativo móvel em nosso <a href="https://github.com/yosietserga" target="_blank">Github Repos</a>. Você pode fazer uma doação também.'
        },
        'fr-fr': {
            'Time Interval': 'Intervalle de temps',
            'Price Change': 'Changement de prix',
            'Min': 'Le minimum',
            'Max': 'Le maximum',
            'Refresh': 'Rafraîchir',
            'Currency': 'Devise',
            'Last Price': 'Dernier prix',
            'Volume': 'Le volume',
            'Volume Change': 'Changement de volume',
            'Since Opened': 'Depuis l\'ouverture',
            'Acum': 'Acum',
            'AVG': 'AVG',
            'Hide': 'Cacher',
            'Show': 'Spectacle',
            'Calculator': 'Calculatrice',
            'Price': 'Prix',
            'Buy': 'Acheter',
            'Sell': 'Vendre',
            'High': 'élevé',
            'Low': 'Low',
            'Last': 'Durer',
            'Change': 'Changement',
            'Improve': 'Améliorer',
            'Trades': 'Métiers',
            'Help Us to Improve': 'Aidez-nous à améliorer',
            'WorkingOn': 'Nous travaillons rapidement pour vous offrir le meilleur outil de trading jamais créé pour huobi global. Notre objectif est de vous fournir un outil unifié via des applications Web et mobiles qui détecte rapidement les cryptos de la pompe et du vidage.',
            'Make a donation': 'S\'il vous plaît nous donner vos suggestions sur comment pouvons-nous améliorer l\'extension du navigateur et l\'application mobile dans notre <a href="https://github.com/yosietserga" target="_blank">Github Repos</a>. Vous pouvez aussi faire un don.'
        },
        'de-de': {
            'Time Interval': 'Tijdsinterval',
            'Price Change': 'Prijs verandering',
            'Min': 'Min',
            'Max': 'Max',
            'Refresh': 'Verversen',
            'Currency': 'Valuta',
            'Last Price': 'Laatste prijs',
            'Volume': 'Volume',
            'Volume Change': 'Volumewijziging',
            'Since Opened': 'Sinds geopend',
            'Acum': 'Acum',
            'AVG': 'AVG',
            'Hide': 'Verbergen',
            'Show': 'Laten zien',
            'Calculator': 'Rekenmachine',
            'Price': 'Prijs',
            'Buy': 'Kopen',
            'Sell': 'Verkopen',
            'High': 'Hoog',
            'Low': 'Laag',
            'Last': 'Laatste',
            'Change': 'Verandering',
            'Improve': 'Verbeteren',
            'Trades': 'Trades',
            'Help Us to Improve': 'Help ons om te verbeteren',
            'WorkingOn': 'We werken er hard aan om u de beste trading tool te geven die ooit voor huobi global is gemaakt. Ons doel is om u een uniform hulpmiddel te bieden via web- en mobiele apps die de pomp en de cryptos van de dump vroegtijdig detecteren',
            'Make a donation': 'Geef ons uw suggesties over hoe we de browserextensie en de mobiele app in onze kunnen verbeteren <a href="https://github.com/yosietserga" target="_blank">Github Repos</a>. U kunt ook een gift doen.'
        },
        'ko-kr': {
            'Time Interval': '시간 간격',
            'Price Change': '가격 변동',
            'Min': '최저한의',
            'Max': '최고',
            'Refresh': '새롭게 하다',
            'Currency': '통화',
            'Last Price': '마지막 가격',
            'Volume': '음량',
            'Volume Change': '볼륨 변경',
            'Since Opened': '이후 개설 됨',
            'Acum': '누적 된',
            'AVG': '평균',
            'Hide': '숨는 장소',
            'Show': '보여 주다',
            'Calculator': '계산자',
            'Price': '가격',
            'Buy': '사다',
            'Sell': '팔다',
            'High': '높은',
            'Low': '낮은',
            'Last': '마지막',
            'Change': '변화',
            'Improve': '돌리다',
            'Trades': '거래',
            'Help Us to Improve': '개선 할 수 있도록 도와주세요.',
            'WorkingOn': '우리는 huobi 글로벌을 위해 만들어진 최고의 거래 도구를 제공하기 위해 빠르게 작업하고 있습니다. 우리의 목표 초기에 펌프 및 덤프의 암호를 감지하는 웹 및 모바일 앱을 통해 통합 도구를 제공하는 것입니다.',
            'Make a donation': '제안 해주세요.에있는 브라우저 확장 프로그램과 모바일 앱을 어떻게 개선 할 수 있을까요 그만큼 <a href="https://github.com/yosietserga" target="_blank">Github Repos</a>. 기부도 할 수 있습니다.'
        },
        'ru-ru': {
            'Time Interval': 'интервал времени',
            'Price Change': 'Изменение цены',
            'Min': 'минимальный',
            'Max': 'максимальная',
            'Refresh': 'обновление',
            'Currency': 'валюта',
            'Last Price': 'Последняя цена',
            'Volume': 'объем',
            'Volume Change': 'Изменение громкости',
            'Since Opened': 'С момента открытия',
            'Acum': 'накопленный',
            'AVG': 'средний',
            'Hide': 'Спрятать',
            'Show': 'Шоу',
            'Calculator': 'Калькулятор',
            'Price': 'цена',
            'Buy': 'купить',
            'Sell': 'продавать',
            'High': 'высоко',
            'Low': 'Низкий',
            'Last': 'Прошлой',
            'Change': '+ Изменить',
            'Improve': 'улучшать',
            'Trades': 'Торги',
            'Help Us to Improve': 'Помогите нам улучшить',
            'WorkingOn': 'Мы работаем быстро, чтобы предоставить вам лучший торговый инструмент, когда-либо созданный для huobi global. Наша цель - предоставить вам унифицированный инструмент с помощью веб-приложений и мобильных приложений, которые на ранних этапах обнаруживают криптографическую информацию о насосах и дампах.',
            'Make a donation': 'Пожалуйста, дайте нам свои предложения о том, как мы можем улучшить расширение браузера и мобильное приложение в нашем <a href="https://github.com/yosietserga" target="_blank">Github Repos</a>. Вы можете сделать пожертвование тоже.'
        },
        'es-es': {
            'Time Interval': 'Intervalo de Tiempo',
            'Price Change': 'Cambio del Precio',
            'Min': 'Min',
            'Max': 'Max',
            'Refresh': 'Refrescar',
            'Currency': 'Moneda',
            'Last Price': 'Ultimo Precio',
            'Volume': 'Volumen',
            'Volume Change': 'Cambio del Volumen',
            'Since Opened': 'Desde Abriste',
            'Acum': 'Acum',
            'AVG': 'AVG',
            'Hide': 'Ocultar',
            'Show': 'Mostrar',
            'Calculator': 'Calculator',
            'Price': 'Precio',
            'Buy': 'Comprar',
            'Sell': 'Vender',
            'High': 'Alto',
            'Low': 'Bajo',
            'Last': 'Ultimo',
            'Change': 'Cambio',
            'Improve': 'Mejorar',
            'Selling': 'Vendiendo',
            'Buying': 'Comprando',
            'Depth': 'Profundidad',
            'Trades': 'Transacciones',
            'Help Us to Improve': 'Ay&uacute;danos a Mejorar',
            'WorkingOn': 'Estamos trabajando rápido para ofrecerle la mejor herramienta comercial jamás creada para huobi global. Nuestro objetivo es ofrecerle una herramienta unificada a través de aplicaciones web y móviles que detectan a tiempo las subidas y bajadas de las cryptos.',
            'Make a donation': 'Por favor, danos tus sugerencias sobre cómo podemos mejorar la extensión del navegador y la aplicación móvil en nuestros <a href="https://github.com/yosietserga" target="_blank">Github Repos</a>. También puedes hacer una donación.'
        },
        'zh-cn': {
            'Time Interval': '時間間隔',
            'Price Change': '價格變動',
            'Min': '最低限度',
            'Max': '最大值',
            'Refresh': 'Refresh',
            'Currency': '貨幣',
            'Last Price': '最後價格',
            'Volume': '量',
            'Volume Change': '成交量變化',
            'Since Opened': '自開業以來',
            'Acum': '積累',
            'AVG': '平均',
            'Hide': '隱藏',
            'Show': '節目',
            'Calculator': '計算器',
            'Price': '價錢',
            'Buy': '購買',
            'Sell': '賣',
            'High': '最高价',
            'Low': '最低价',
            'Last': '持續',
            'Change': '涨幅',
            'Improve': '提高',
            'Trades': '交易',
            'Help Us to Improve': '帮助我们改进',
            'WorkingOn': '我们正在努力为您提供有史以来为huobi global制作的最佳交易工具. 我们的目标是通过早期检测到的网络和移动应用为您提供统一的工具 the pump and dump\'s cryptos',
            'Make a donation': '请告诉我们您如何在我们的 <a href="https://github.com/yosietserga" target="_blank">Github Repos</a>. 中改进浏览器扩展和移动应用程序的建议. 你也可以捐款'
        }
    },
    'binance': {
        'en': {
            'Time Interval': 'Time Interval',
            'Price Change': 'Price Change',
            'Min': 'Min',
            'Max': 'Max',
            'Refresh': 'Refresh',
            'Currency': 'Currency',
            'Last Price': 'Last Price',
            'Volume': 'Volume',
            'Volume Change': 'Volume Change',
            'Since Opened': 'Since Opened',
            'Acum': 'Accum',
            'AVG': 'AVG',
            'Hide': 'Hide',
            'Show': 'Show',
            'Calculator': 'Calculator',
            'Price': 'Price',
            'Buy': 'Buy',
            'Sell': 'Sell',
            'High': 'High',
            'Low': 'Low',
            'Last': 'Last',
            'Change': 'Change',
            'Improve': 'Improve',
            'Selling': 'Selling',
            'Buying': 'Buying',
            'Depth': 'Depth',
            'Trades': 'Trades',
            'Help Us to Improve': 'Help Us to Improve',
            'WorkingOn': 'We are working fast to give you the best trading tool ever made for huobi global. Our goal is to bring you a unified tool through web and mobile apps that detect early the pump and dump\'s cryptos',
            'Make a donation': 'Please give us your suggestions on how can we improve the browser extension and the mobile app in our <a href="https://github.com/yosietserga" target="_blank">Github Repos</a>. You can make a donation, too.'
        },
        'tr': {
            'Time Interval': 'Zaman aralığı',
            'Price Change': 'fiyat değişiklikleri',
            'Min': 'Asgari',
            'Max': 'Maksimum',
            'Refresh': 'Yenile',
            'Currency': 'Para birimi',
            'Last Price': 'Son fiyat',
            'Volume': 'Hacim',
            'Volume Change': 'Hacim Değişimi',
            'Since Opened': 'Açıldığından beri',
            'Acum': 'Birikmiş',
            'AVG': 'AVG',
            'Hide': 'Saklamak',
            'Show': 'Göstermek',
            'Calculator': 'Hesap makinesi',
            'Price': 'Fiyat',
            'Buy': 'Satın almak',
            'Sell': 'Satmak',
            'High': 'Yüksek',
            'Low': 'Düşük',
            'Last': 'Son',
            'Change': 'Değişiklik',
            'Improve': 'Iyileştirmek',
            'Trades': 'İşlemler',
            'Help Us to Improve': 'Geliştirmemize Yardım Edin',
            'WorkingOn': 'Size şimdiye kadar huobi global için üretilmiş en iyi yatırım aracını sunmak için hızlı çalışıyoruz. Amacımız, pompanın ve boşaltma kriptolarının erken dönemlerini tespit eden web ve mobil uygulamalar aracılığıyla size birleşik bir araç sunmaktır.',
            'Make a donation': 'Lütfen bize tarayıcı uzantısını ve mobil uygulamamızı <a href="https://github.com/yosietserga" target="_blank">Github Repos</a>. Siz de bağış yapabilirsiniz.'
        },
        'vn': {
            'Time Interval': 'Khoảng thời gian',
            'Price Change': 'Thay đổi giá',
            'Min': 'Tối thiểu',
            'Max': 'Tối đa',
            'Refresh': 'Làm tươi',
            'Currency': 'Tiền tệ',
            'Last Price': 'Giá cuối cùng',
            'Volume': 'Âm lượng',
            'Volume Change': 'Thay đổi âm lượng',
            'Since Opened': 'Kể từ khi mở',
            'Acum': 'Tích lũy',
            'AVG': 'AVG',
            'Hide': 'Ẩn giấu',
            'Show': 'Chỉ',
            'Calculator': 'Máy tính',
            'Price': 'Giá bán',
            'Buy': 'Mua',
            'Sell': 'Bán',
            'High': 'Cao',
            'Low': 'Thấp',
            'Last': 'Cuối cùng',
            'Change': 'Thay đổi',
            'Improve': 'Cải tiến',
            'Trades': 'Giao dịch',
            'Help Us to Improve': 'Giúp chúng tôi cải thiện',
            'WorkingOn': 'Chúng tôi đang làm việc nhanh chóng để cung cấp cho bạn công cụ giao dịch tốt nhất từng được tạo ra cho huobi toàn cầu. Mục tiêu của chúng tôi là mang đến cho bạn một công cụ hợp nhất thông qua các ứng dụng web và di động phát hiện sớm tiền điện tử của máy bơm',
            'Make a donation': 'Vui lòng cho chúng tôi đề xuất của bạn về cách chúng tôi có thể cải thiện tiện ích mở rộng trình duyệt và ứng dụng di động trong <a href="https://github.com/yosietserga" target="_blank">Github Repos</a>. Bạn cũng có thể đóng góp.'
        },
        'pt': {
            'Time Interval': 'Intervalo de tempo',
            'Price Change': 'Mudança de preço',
            'Min': 'Min',
            'Max': 'Max',
            'Refresh': 'Atualizar',
            'Currency': 'Moeda',
            'Last Price': 'Último preço',
            'Volume': 'Volume',
            'Volume Change': 'Mudança de volume',
            'Since Opened': 'Desde que abriu',
            'Acum': 'Acumulado',
            'AVG': 'AVG',
            'Hide': 'Ocultar',
            'Show': 'Exposição',
            'Calculator': 'Calculadora',
            'Price': 'Preço',
            'Buy': 'Comprar',
            'Sell': 'Vender',
            'High': 'Alto',
            'Low': 'Baixo',
            'Last': 'Último',
            'Change': 'Mudança',
            'Improve': 'Melhorar',
            'Trades': 'Comércios',
            'Help Us to Improve': 'Ajude-nos a melhorar',
            'WorkingOn': 'Estamos trabalhando rapidamente para oferecer a melhor ferramenta de negociação já feita para o mundo huobi. Nosso objetivo é trazer a você uma ferramenta unificada através de aplicativos web e móveis que detectam precocemente os criptos de bombas e lixões',
            'Make a donation': 'Por favor, dê-nos as suas sugestões sobre como podemos melhorar a extensão do navegador e o aplicativo móvel em nosso <a href="https://github.com/yosietserga" target="_blank">Github Repos</a>. Você pode fazer uma doação também.'
        },
        'fr': {
            'Time Interval': 'Intervalle de temps',
            'Price Change': 'Changement de prix',
            'Min': 'Le minimum',
            'Max': 'Le maximum',
            'Refresh': 'Rafraîchir',
            'Currency': 'Devise',
            'Last Price': 'Dernier prix',
            'Volume': 'Le volume',
            'Volume Change': 'Changement de volume',
            'Since Opened': 'Depuis l\'ouverture',
            'Acum': 'Acum',
            'AVG': 'AVG',
            'Hide': 'Cacher',
            'Show': 'Spectacle',
            'Calculator': 'Calculatrice',
            'Price': 'Prix',
            'Buy': 'Acheter',
            'Sell': 'Vendre',
            'High': 'élevé',
            'Low': 'Low',
            'Last': 'Durer',
            'Change': 'Changement',
            'Improve': 'Améliorer',
            'Trades': 'Métiers',
            'Help Us to Improve': 'Aidez-nous à améliorer',
            'WorkingOn': 'Nous travaillons rapidement pour vous offrir le meilleur outil de trading jamais créé pour huobi global. Notre objectif est de vous fournir un outil unifié via des applications Web et mobiles qui détecte rapidement les cryptos de la pompe et du vidage.',
            'Make a donation': 'S\'il vous plaît nous donner vos suggestions sur comment pouvons-nous améliorer l\'extension du navigateur et l\'application mobile dans notre <a href="https://github.com/yosietserga" target="_blank">Github Repos</a>. Vous pouvez aussi faire un don.'
        },
        'de': {
            'Time Interval': 'Tijdsinterval',
            'Price Change': 'Prijs verandering',
            'Min': 'Min',
            'Max': 'Max',
            'Refresh': 'Verversen',
            'Currency': 'Valuta',
            'Last Price': 'Laatste prijs',
            'Volume': 'Volume',
            'Volume Change': 'Volumewijziging',
            'Since Opened': 'Sinds geopend',
            'Acum': 'Acum',
            'AVG': 'AVG',
            'Hide': 'Verbergen',
            'Show': 'Laten zien',
            'Calculator': 'Rekenmachine',
            'Price': 'Prijs',
            'Buy': 'Kopen',
            'Sell': 'Verkopen',
            'High': 'Hoog',
            'Low': 'Laag',
            'Last': 'Laatste',
            'Change': 'Verandering',
            'Improve': 'Verbeteren',
            'Trades': 'Trades',
            'Help Us to Improve': 'Help ons om te verbeteren',
            'WorkingOn': 'We werken er hard aan om u de beste trading tool te geven die ooit voor huobi global is gemaakt. Ons doel is om u een uniform hulpmiddel te bieden via web- en mobiele apps die de pomp en de cryptos van de dump vroegtijdig detecteren',
            'Make a donation': 'Geef ons uw suggesties over hoe we de browserextensie en de mobiele app in onze kunnen verbeteren <a href="https://github.com/yosietserga" target="_blank">Github Repos</a>. U kunt ook een gift doen.'
        },
        'kr': {
            'Time Interval': '시간 간격',
            'Price Change': '가격 변동',
            'Min': '최저한의',
            'Max': '최고',
            'Refresh': '새롭게 하다',
            'Currency': '통화',
            'Last Price': '마지막 가격',
            'Volume': '음량',
            'Volume Change': '볼륨 변경',
            'Since Opened': '이후 개설 됨',
            'Acum': '누적 된',
            'AVG': '평균',
            'Hide': '숨는 장소',
            'Show': '보여 주다',
            'Calculator': '계산자',
            'Price': '가격',
            'Buy': '사다',
            'Sell': '팔다',
            'High': '높은',
            'Low': '낮은',
            'Last': '마지막',
            'Change': '변화',
            'Improve': '돌리다',
            'Trades': '거래',
            'Help Us to Improve': '개선 할 수 있도록 도와주세요.',
            'WorkingOn': '우리는 huobi 글로벌을 위해 만들어진 최고의 거래 도구를 제공하기 위해 빠르게 작업하고 있습니다. 우리의 목표 초기에 펌프 및 덤프의 암호를 감지하는 웹 및 모바일 앱을 통해 통합 도구를 제공하는 것입니다.',
            'Make a donation': '제안 해주세요.에있는 브라우저 확장 프로그램과 모바일 앱을 어떻게 개선 할 수 있을까요 그만큼 <a href="https://github.com/yosietserga" target="_blank">Github Repos</a>. 기부도 할 수 있습니다.'
        },
        'ru': {
            'Time Interval': 'интервал времени',
            'Price Change': 'Изменение цены',
            'Min': 'минимальный',
            'Max': 'максимальная',
            'Refresh': 'обновление',
            'Currency': 'валюта',
            'Last Price': 'Последняя цена',
            'Volume': 'объем',
            'Volume Change': 'Изменение громкости',
            'Since Opened': 'С момента открытия',
            'Acum': 'накопленный',
            'AVG': 'средний',
            'Hide': 'Спрятать',
            'Show': 'Шоу',
            'Calculator': 'Калькулятор',
            'Price': 'цена',
            'Buy': 'купить',
            'Sell': 'продавать',
            'High': 'высоко',
            'Low': 'Низкий',
            'Last': 'Прошлой',
            'Change': '+ Изменить',
            'Improve': 'улучшать',
            'Trades': 'Торги',
            'Help Us to Improve': 'Помогите нам улучшить',
            'WorkingOn': 'Мы работаем быстро, чтобы предоставить вам лучший торговый инструмент, когда-либо созданный для huobi global. Наша цель - предоставить вам унифицированный инструмент с помощью веб-приложений и мобильных приложений, которые на ранних этапах обнаруживают криптографическую информацию о насосах и дампах.',
            'Make a donation': 'Пожалуйста, дайте нам свои предложения о том, как мы можем улучшить расширение браузера и мобильное приложение в нашем <a href="https://github.com/yosietserga" target="_blank">Github Repos</a>. Вы можете сделать пожертвование тоже.'
        },
        'es': {
            'Time Interval': 'Intervalo de Tiempo',
            'Price Change': 'Cambio del Precio',
            'Min': 'Min',
            'Max': 'Max',
            'Refresh': 'Refrescar',
            'Currency': 'Moneda',
            'Last Price': 'Ultimo Precio',
            'Volume': 'Volumen',
            'Volume Change': 'Cambio del Volumen',
            'Since Opened': 'Desde Abriste',
            'Acum': 'Acum',
            'AVG': 'AVG',
            'Hide': 'Ocultar',
            'Show': 'Mostrar',
            'Calculator': 'Calculator',
            'Price': 'Precio',
            'Buy': 'Comprar',
            'Sell': 'Vender',
            'High': 'Alto',
            'Low': 'Bajo',
            'Last': 'Ultimo',
            'Change': 'Cambio',
            'Improve': 'Mejorar',
            'Selling': 'Vendiendo',
            'Buying': 'Comprando',
            'Depth': 'Profundidad',
            'Trades': 'Transacciones',
            'Help Us to Improve': 'Ay&uacute;danos a Mejorar',
            'WorkingOn': 'Estamos trabajando rápido para ofrecerle la mejor herramienta comercial jamás creada para huobi global. Nuestro objetivo es ofrecerle una herramienta unificada a través de aplicaciones web y móviles que detectan a tiempo las subidas y bajadas de las cryptos.',
            'Make a donation': 'Por favor, danos tus sugerencias sobre cómo podemos mejorar la extensión del navegador y la aplicación móvil en nuestros <a href="https://github.com/yosietserga" target="_blank">Github Repos</a>. También puedes hacer una donación.'
        },
        'cn': {
            'Time Interval': '時間間隔',
            'Price Change': '價格變動',
            'Min': '最低限度',
            'Max': '最大值',
            'Refresh': 'Refresh',
            'Currency': '貨幣',
            'Last Price': '最後價格',
            'Volume': '量',
            'Volume Change': '成交量變化',
            'Since Opened': '自開業以來',
            'Acum': '積累',
            'AVG': '平均',
            'Hide': '隱藏',
            'Show': '節目',
            'Calculator': '計算器',
            'Price': '價錢',
            'Buy': '購買',
            'Sell': '賣',
            'High': '最高价',
            'Low': '最低价',
            'Last': '持續',
            'Change': '涨幅',
            'Improve': '提高',
            'Trades': '交易',
            'Help Us to Improve': '帮助我们改进',
            'WorkingOn': '我们正在努力为您提供有史以来为huobi global制作的最佳交易工具. 我们的目标是通过早期检测到的网络和移动应用为您提供统一的工具 the pump and dump\'s cryptos',
            'Make a donation': '请告诉我们您如何在我们的 <a href="https://github.com/yosietserga" target="_blank">Github Repos</a>. 中改进浏览器扩展和移动应用程序的建议. 你也可以捐款'
        }
    }
};

const exchange = getExchangeName();
const url = getUrl();
let __langs, defaultLang, __hl;

if (exchange == 'huobi') {
      __langs = ['en-us', 'th-th', 'tr-tr', 'vi-vi', 'pt-br', 'pt-pt', 'fr-fr', 'de-de', 'ko-kr', 'ru-ru', 'es-es', 'zh-cn'];
      defaultLang = 'zh-cn';
      __hl = isset(localStorage.lang) && !empty(localStorage.lang) && __langs.indexOf( localStorage.lang ) != -1 ? localStorage.lang : null;
} else if (exchange == 'binance') {
      __langs = ['en','tr','vn','pt','fr','de','kr','ru','es','cn'];
      defaultLang = 'en';
      __hl = isset(localStorage.lang) && !empty(localStorage.lang) && __langs.indexOf( localStorage.lang ) != -1 ? localStorage.lang : null;
} else if (exchange == 'zb') {
      __langs = ['en','cn'];
      defaultLang = 'en';
      __hl = isset(window.GLOBAL) && isset(window.GLOBAL.LAN) && !empty(window.GLOBAL.LAN) && __langs.indexOf( window.GLOBAL.LAN ) != -1 ? window.GLOBAL.LAN : null;
}

const hl = __hl ? __hl : defaultLang;
const lang = languages[ exchange ][ hl ];
